# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'FollowUpappid' do
  use_frameworks!
	pod 'IBMCloudAppID', '6.0.0'
  pod 'Alamofire', '4.8.2'
  pod 'BMSPush', '3.4.3'
end
