# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘FollowUpappid’ do
  use_frameworks!
	pod 'BluemixAppID'
    pod 'Alamofire', '~> 4.5'
    pod 'BMSPush', '~> 3.0'
end
